set(CURRENT_PROJECT_NAME "p032")
set(${CURRENT_PROJECT_NAME}_MIN_CMAKE_VER 2.8)
set(${CURRENT_PROJECT_NAME}_CMAKE_HOST_CONFIGS_ROOT_DIR "${CMAKE_CURRENT_SOURCE_DIR}/cmake")
set(${CURRENT_PROJECT_NAME}_ROOT_PATH "${CMAKE_CURRENT_SOURCE_DIR}")
set(PLATFORM_CMAKE_FILE_PREFIX "pl_")
set(PLATFORM_CMAKE_FILE_SUFFIX ".cmake")
set(CMAKE_TOOLCHAIN_FILE "${${CURRENT_PROJECT_NAME}_ROOT_PATH}/tc.cmake")

